version: "2"
services:
    # explorer:
    #     build: ./models
    #     volumes:
    #       - ./:/home/jovyan/work:rw
    #       - ./models/:/usr/local/lib/python3.6/site-packages/network-adequacy:ro
    #     command: bash -c "start-notebook.sh --NotebookApp.token=''"
    #     ports:
    #       - 8888:8888
    #     environment:
    #       - PYTHONPATH=/home/jovyan/work

    backend:
        volumes:
          - ./backend/app.py:/var/local/app.py
          - .flake8:/var/local/.flake8:ro
        build: ./web-app/backend
        ports:
            - "80:5000"
        command: python app.py

    mongo:
        image: mongo:3.4.0
        ports:
          - "27017:27017"

    mongo-seed:
        build: ./data
        links:
          - mongo

    webapp:
        volumes:
          - ./web-app/frontend/src:/usr/src/app/src
          - ./web-app/frontend/public:/usr/src/app/public
        command: npm run start
        build: ./web-app/frontend
        links:
          - backend
        ports:
          - 3000:3000
        depends_on:
          - mongo
          - mongo-seed
          - backend
