version: "2"
services:
  explorer:
    build:
      context: .
    volumes:
      - ./:/home/jovyan/work:rw
      - .:/usr/local/lib/python3.6/site-packages/claims_to_quality:ro
    command: bash -c "start-notebook.sh --NotebookApp.token=''"
    ports:
      - 8888:8888
    environment:
      - PYTHONPATH=/home/jovyan/work
